version: "3.9"
services:
  c2:
    build:
      context: C2
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    container_name: log4j-c2
    volumes:
      - ./C2/found_secret_data.txt:/C2/found_secret_data.txt
    networks:
      network:
        ipv4_address: 172.25.0.2
      
  vulnerable-application:
    build:
      context: vulnerable-application
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: log4j-vulnerable-application
    environment:
      - C2_IP = 172.25.0.2
    networks:
      network:
        ipv4_address: 172.25.0.3
    depends_on:
      - c2
  initial_exploit:
    build:
      context: initial_exploit
      dockerfile: Dockerfile
    container_name: log4j-initial_exploit
    networks:
      network:
        ipv4_address: 172.25.0.4
networks:
  network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
